name: mahlak_nem
description: A new Flutter project

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.3.2
  flutter_svg: ^2.0.6
  flutter_animate: ^4.0.0
  shimmer: ^2.0.0
  provider: ^6.0.5
  form_field_validator: ^1.1.0
  image: ^4.5.4
  intl: ^0.20.2
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
